# escape=`
FROM plugins/base:windows-1803

LABEL maintainer="Drone.IO Community <drone-dev@googlegroups.com>" `
  org.label-schema.name="Drone Manifest" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ENV MANIFEST_TOOL_VERSION 0.9.0

RUN New-Item -ItemType directory -Path 'c:/bin'; `
    Invoke-WebRequest ('https://github.com/estesp/manifest-tool/releases/download/v{0}/manifest-tool-windows-amd64.exe' -f $env:MANIFEST_TOOL_VERSION) -OutFile 'c:/bin/manifest-tool.exe';

ADD release/windows/amd64/drone-manifest.exe c:/bin/drone-manifest.exe
ENTRYPOINT [ "c:\\bin\\drone-manifest.exe" ]
